Use oc binary from the payload instead user provided
If user is using older version of oc binary then some of the
functionality doesn't work as expected due to server and client
mismatch.

```
$ oc adm certificate approve csr-chcck
No resources found
error: no kind "CertificateSigningRequest" is registered for version "certificates.k8s.io/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
```