Remove render machine config which have pull secret info
Till now we are removing all the rendered machine config for master except the latest one.
In this PR we keep the latest one and the one before the last because of upstream bug
https://issues.redhat.com/browse/OCPBUGS-4049 introduced by
https://github.com/openshift/machine-config-operator/commit/1671a453f1a95ff9e3720719c4151f289e2fdd0c

```
I1123 10:31:08.119905    4150 run.go:19] Running: podman pull -q --authfile /var/lib/kubelet/config.json quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ffa3568233298408421ff7da60e5c594fb63b2551c6ab53843eb51c8cf6838ba
Error: initializing source docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ffa3568233298408421ff7da60e5c594fb63b2551c6ab53843eb51c8cf6838ba: reading manifest sha256:ffa3568233298408421ff7da60e5c594fb63b2551c6ab53843eb51c8cf6838ba in quay.io/openshift-release-dev/ocp-v4.0-art-dev: unauthorized: access to the requested resource is not authorized
```

This is still a workaround because ideally mco should able to reconcile
in case there is no pull secret on the cluster (OKD usecase).

How this workaround work:-

With this PR, after the snc.sh script runs, the state of machine config operator will
be degraded (see example below), but this is not blocking snc.sh script to run successfully.
Ideally mco should able to reconcile in case there is no pull secret on the cluster (OKD usecase).

```
$ oc get co machine-config
NAME             VERSION       AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
machine-config   4.12.0-rc.1   True        False         True       93m     Failed to resync 4.12.0-rc.1 because: error during syncRequiredMachineConfigPools: [timed out waiting for the condition, error pool master is not ready, retrying. Status: (pool degraded: true total: 1, ready 0, updated: 0, unavailable: 0)]
```

Once this bundle is consumed by CRC, MCO will find the user pull secret and
start reconciling which makes the machine-config to available again.

If we delete the second last MC (like we are doing till now) then machin-config
operator fails with below error and not able to reconcile because it points
to an rendered machine config which already deleted.

```
$ oc logs machine-config-daemon-6pczk -n openshift-machine-config-operator
[...]
E1123 08:41:54.131381    3674 writer.go:200] Marking Degraded due to: prepping update: machineconfig.machineconfiguration.openshift.io "rendered-master-1217872a72f41af7514c83cc6defb701" not found
```