Add retry for virsh commands
Since RHEL-8.3 now uses libvirtd.socket for service activation, on
the CI side we are observing connection timeout during virsh commands.

```
+ sudo virsh start crc-2ss7l-master-0
error: failed to connect to the hypervisor
error: Cannot recv data: Connection reset by peer
```