Microshift: Add microshift-olm package
Looks like from 4.15 microshift-olm package is dependency for microshift
so this PR adds it to avoid following error
```
ERROR: BlueprintsError: microshift: DNF error occurred: MarkingErrors: Error occurred when marking packages for installation: Problems in request:
missing packages: microshift-olm-4.15.0~rc.0
```