microshift: Install runc and containernetworking-plugins package
These package are required otherwise in the CI (fresh RHEL-9.2)
following error occur
```
$ scripts/image-builder/cleanup.sh -full
Error: default OCI runtime "runc" not found: invalid argument

$ scripts/image-builder/build.sh -microshift_rpms /tmp/tmp-rpmIz8 -pull_secret_file /var/lib/jenkins/workspace/eng-crc-microshift/pullsecret.json -lvm_sysroot_size 15360 -authorized_keys_file /var/lib/jenkins/workspace/eng-crc-microshift/id_ecdsa_crc.pub
[...]
time="2023-05-24T08:24:43-04:00" level=warning msg="Failed to load cached network config: network podman not found in CNI cache, falling back to loading network podman from disk"
time="2023-05-24T08:24:43-04:00" level=warning msg="1 error occurred:\n\t* plugin type=\"tuning\" failed (delete): failed to find plugin \"tuning\" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin]\n\n"
Error: plugin type="bridge" failed (add): failed to find plugin "bridge" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin]
```