Use sudo for virsh commands as part of preflight checks
openshift/okd bundles use `qemu+tcp` connection so that doesn't need the
'sudo' to get the details about network, uri and capabilities but for
microshift bundle we use same preflight checks and use `qemu:///system`
uri which need `sudo` to get those details otherwise the CI fails with
following error:
```
+ '[' microshift == okd ']'
+ virsh -c qemu:///system uri
error: failed to connect to the hypervisor
```