createdisk: download qemu-static package instead install
This pr downloads the qemu-static package from the fedora repo and put
it to `packages` dir instead installing it because if we install and
then remove the fedora repo which is done  as part of
2dbbc98038db922ca9eb3885f468fd8430717a86 commit then it create a
deployment layer for rpm-ostree. Now when we try to install other
packages it is going to again check if `qemu-static` package available
because rpm-ostree requires all previously layered packages to still be
resolvable when you install new ones. If any of them are missing
(like qemu-user-static-x86), the operation fails with following error.

This PR try to solve  it by not installing but just download it and
adding this package as part of additional_packages variable so that it
can be part of local repo and install without error.

```
 + ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i id_ecdsa_crc core@192.168.126.11 -- 'sudo rpm-ostree install cloud-init gvisor-tap-vsock-gvforwarder'
Warning: Permanently added '192.168.126.11' (ED25519) to the list of known hosts.
Checking out tree 70544e8...done
Enabled rpm-md repositories: local
Importing rpm-md...done
rpm-md repo 'local' (cached); generated: 2025-06-30T17:16:37Z solvables: 173
error: Packages not found: qemu-user-static-x
```