createdisk-library: Don't use double qoute for $*
In shell $* interpreted as single word so when used with double quote
it make all the word as single one and package installation failed
as following if there is one than one package name.
```
+ install_additional_packages 192.168.13.11 hyperv-daemons cifs-utils
+ local IP=192.168.13.11
+ shift
++ mktemp -d tmp-rpmXXX
+ local pkgDir=tmp-rpmM5Z
+ mkdir -p tmp-rpmM5Z/packages
+ sudo yum download --downloadonly --downloaddir tmp-rpmM5Z/packages 'hyperv-daemons cifs-utils' --resolve
Updating Subscription Management repositories.
Last metadata expiration check: 0:10:30 ago on Friday 30 September 2022 05:48:16 AM UTC.
No package hyperv-daemons cifs-utils available.
Exiting due to strict setting.
Error: No package hyperv-daemons cifs-utils available.
```