Don't delete only 1 worker-render instead 2
As part of 3bf3cf5ed660c3a19ac6720e983e333618276876, we delete all
the master and worker render except latest 2 but as part of machine
config once the pull secret is removed the master render happen twice
but worker is only once.
```
$ oc get mc --sort-by=.metadata.creationTimestamp --no-headers -oname
machineconfig.machineconfiguration.openshift.io/99-openshift-machineconfig-master-dummy-networks
machineconfig.machineconfiguration.openshift.io/99-node-sizing-for-crc
machineconfig.machineconfiguration.openshift.io/99-master-ssh
machineconfig.machineconfiguration.openshift.io/99-worker-ssh
machineconfig.machineconfiguration.openshift.io/01-worker-container-runtime
machineconfig.machineconfiguration.openshift.io/99-master-generated-registries
machineconfig.machineconfiguration.openshift.io/00-master
machineconfig.machineconfiguration.openshift.io/01-master-kubelet
machineconfig.machineconfiguration.openshift.io/01-master-container-runtime
machineconfig.machineconfiguration.openshift.io/99-worker-generated-registries
machineconfig.machineconfiguration.openshift.io/00-worker
machineconfig.machineconfiguration.openshift.io/01-worker-kubelet
machineconfig.machineconfiguration.openshift.io/rendered-master-506946fd9bf2403f086a27f7769de5b7
machineconfig.machineconfiguration.openshift.io/rendered-worker-71346ec1c2025739cb6b1a059f592ded
machineconfig.machineconfiguration.openshift.io/rendered-master-667268f1a9735d0000165f5bd2ba6eb9
machineconfig.machineconfiguration.openshift.io/rendered-master-6e87f382d2fb4b6608169e266549d361
machineconfig.machineconfiguration.openshift.io/rendered-worker-06237aa10928dd74d82660019c4c26c8
```

This should avoid following failure
```
+ grep rendered-worker
+ head -n -2
+ xargs -t ./openshift-clients/linux/oc delete
./openshift-clients/linux/oc delete
error: You must provide one or more resources by argument or filename.
```