Enforce a single search registry
Enforce "docker.io" to be the only search registry.  Short-name
resolution for remote clients is not fully supported since there is no
means to prompt.  Enforcing a single registry  works around the problem
since prompting only fires with more than one search registry.

Without this patch docker/podman client not able to pull short-name images when using remote socket.
```
$ eval $(crc podman-env)
$ podman-remote pull httpd:latest
Error: short-name resolution enforced but cannot prompt without a TTY
```

- https://github.com/containers/podman/commit/6f36a47ac2bc5dee2785043231a6e0734c9087cf
- https://github.com/containers/podman/issues/11489