Issue #127 Increase the timeout for kubelet-bootstrap-cred-manager pod termination
Currently, the timeout is 60s which is not enough for kubelet-bootstrap-cred-manager pod
to terminated properly and this also lead to error of deleting the image.
we should increase it to 120s to be in safer side.

```
daemonset.apps "kubelet-bootstrap-cred-manager" deleted
error: timed out waiting for the condition
```